### PR TITLE
Target platforms for 2025-09 and 2025-06 milestone

### PR DESCRIPTION
**Pull request by aparnaargade**
Setting minimum Java version to JavaSE-21.
Using latest tycho version 4.0.12

### CODE REVIEW

**Review by LorenzoBettini — CHANGES_REQUESTED** [review]
The build fails due to an old version of the upload action that should be updated. Besides that, everything looks good!

**Comment by aparnaargade** [comment]
Build is not happening. It is failing with message "Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/".
@LorenzoBettini  @PatrickTasse  could you look into the setup?

**Comment by LorenzoBettini** [comment]
@aparnaargade it is enough to put 4 instead of 3 in the occurrences of `actions/upload-artifact@v3` in the file https://github.com/eclipse-swtbot/org.eclipse.swtbot/blob/master/.github/workflows/ci.yml

I'm not at a computer now, it's better if you update the PR accordingly.

**Comment by aparnaargade** [comment]
Now build is getting triggered. I also changed Java to 21.  <error message="Could not initialize class org.eclipse.swtbot.swt.finder.keyboard.AWTKeyboardStrategy" type="java.lang.NoClassDefFoundError"><![CDATA[java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.swtbot.swt.finder.keyboard.AWTKeyboardStrategy

**Comment by PatrickTasse** [comment]
The commit and PR header should be changed to '2025-03 and 2025-06'.
Also please squash the commits into one and avoid merge commits (like the plague? ;) )

**Comment by PatrickTasse** [comment]
I tested locally and a base class static initializer only executes once, while a @BeforeClass method executes before each subclass executes its tests. I created a commit with this fix in AbstractSWTShellTest and it ran successfully on top of this PR.

So I created a PR for the fix: https://github.com/eclipse-swtbot/org.eclipse.swtbot/pull/20

However it fails to build on its own due to deprecated actions in ci.yml. So I cherry-picked the commit to update ci.yml from this PR into its own PR: https://github.com/eclipse-swtbot/org.eclipse.swtbot/pull/21

When both of these PRs are merged this PR can be rebased on top of them.

**Review by LorenzoBettini — APPROVED** [review]

**Comment by aparnaargade** [comment]
Thank you @PatrickTasse and @LorenzoBettini for your help!

**Comment by PatrickTasse** [comment]
Note, I fixed this PR header but the merged commit header is wrong, we don't have 2025-09 target platform yet ;)
